// Default seed data — loaded into localStorage on first visit
export const defaultBrands = [
  { id: 'amante',   name: 'Amante' },
  { id: 'vanheusen', name: 'Van Heusen' },
  { id: 'jockey',   name: 'Jockey' },
  { id: 'vstar',    name: 'V-Star' },
  { id: 'bodycare', name: 'Bodycare' },
  { id: 'trylo',    name: 'Trylo' },
];

export const defaultProducts = [
  {
    id: 'prod-001',
    brandId: 'amante',
    name: 'Amante Silk Bralette',
    desc: 'Experience the unparalleled softness of pure silk blends. Delicate lace, intricate detail, and a blush pink hue that embodies quiet luxury. Crafted for breathability and a flawless drape.',
    price: 1499,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcoHGkQ6NDudP3j5DetlrCnHm-6xS3CbXEkzvYc-PFiWZMyfnJz4vsOYoI91C1RE_kfZ-h1Sv4fUlqsEo0Fd1MdxiNRALL-F2luzQaM4L_mp9YvyO_jWVizf57aaLiQrlPl1KmzCtYlAA-OVCbj1Kkjbg_GUfZGSrOVQvuu0b6fCUHuFw7LbyZxHOXB25gDzBDygjvHMn6z1gsaPiPOb9R4qi6Wc9rA5lpb_37LZEBnHk1ePukmmHoW5PxjuYy68a7Nwr3Yz_J1yN-',
    sizeType: 'standard', // 'standard' | 'custom' | 'none'
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-002',
    brandId: 'vanheusen',
    name: 'Van Heusen Bodysuit',
    desc: 'Midnight black sheer mesh bodysuit that effortlessly blends sensuality with sophistication. Premium stretch fabric ensures a second-skin fit for all-day confidence.',
    price: 2199,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8pr1gs99oau4FjuAh71jLPUuERgoERgFvAOS95VPMfWlwgmT_TQv1n1ix99dzTx1JFDUD4qBnW1iZBXSgOw7BQouOaxXxYBdBxYSxsrn2baur873KgAq356tmxfv_D6_uCG1Xwrpw1YAb8TDQeRbLmn1brJ7Rx37wm_I7TQ3fJgyhr-Ie-o4Pm-ro6GcRHNQbWjm4HhBWpTM-5zNlEc74i76oG12eRU6lxCJfG6ETu8WmYAMGtpdE2ZTEf_d3VHFnGVlRvyQk5zW0',
    sizeType: 'standard',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-003',
    brandId: 'jockey',
    name: 'Jockey Seamless Brief',
    desc: 'Ultra-smooth seamless construction eliminates visible lines under any outfit. Made from moisture-wicking microfiber for all-day comfort and freshness.',
    price: 899,
    image: '',
    sizeType: 'standard',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    featured: false,
  },
  {
    id: 'prod-004',
    brandId: 'vstar',
    name: 'V-Star Cotton T-Shirt Bra',
    desc: 'The everyday essential. Pure cotton breathability meets light padding for a natural shape. Ideal for daily wear under any outfit.',
    price: 650,
    image: '',
    sizeType: 'custom',
    sizes: [],
    inStock: true,
    featured: false,
  },
  {
    id: 'prod-005',
    brandId: 'bodycare',
    name: 'Bodycare Essentials Set',
    desc: 'A curated essentials set including a comfortable everyday bra and matching briefs. Soft cotton blend for all-day wearability.',
    price: 599,
    image: '',
    sizeType: 'standard',
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    featured: false,
  },
  {
    id: 'prod-006',
    brandId: 'trylo',
    name: 'Trylo Wire-Free Comfort Bra',
    desc: 'Expertly designed wire-free bra providing all-day support without compromise. Broad cushioned straps and a full-coverage cup for maximum comfort.',
    price: 750,
    image: '',
    sizeType: 'custom',
    sizes: [],
    inStock: true,
    featured: false,
  },
];
